layout (local_size_x = 256) in;

layout(set = 0, binding = 0) uniform Config{
    int matrixCount;
} opData;

layout(set = 0, binding = 1) uniform readonly buffer InputBuffer {
    mat4 modelMatrices[];
} sourceData;

layout(set = 0, binding = 2) uniform buffer OutputBuffer {
    mat3 normalMatrices[];
} outputData;

void main()
{
    if(gl_GlobalInvocationID.x < matrixCount)
    {
        outputData.normalMatrices[gID] = mat3(transpose(inverse(sourceData.modelMatrices[gID])));
    }
}