name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    env:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++

    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Dependencies
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
        sudo apt update
        sudo apt install vulkan-sdk libglm-dev clang
        
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        ${{github.workspace}}/vcpkg/vcpkg integrate install

        ${{github.workspace}}/vcpkg/vcpkg install assimp:x64-linux
        ${{github.workspace}}/vcpkg/vcpkg install openexr:x64-linux
        ${{github.workspace}}/vcpkg/vcpkg install sdl2[vulkan]:x64-linux
        ${{github.workspace}}/vcpkg/vcpkg install stb:x64-linux
        ${{github.workspace}}/vcpkg/vcpkg install vulkan:x64-linux

    - name: Configure CMake Build Debug
      run: cmake -B ${{github.workspace}}/build-linux/build-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
    - name: Compile BananEngine Build Debug
      run: cmake --build ${{github.workspace}}/build-linux/build-debug
      
    - name: Configure CMake Build Release
      run: cmake -B ${{github.workspace}}/build-linux/build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
    - name: Compile BananEngine Build Debug
      run: cmake --build ${{github.workspace}}/build-linux/build-release
      
    - name: Archive compilation output
      uses: actions/upload-artifact@v3
      with:
        name: Build Output Linux
        path: ${{github.workspace}}/build-linux/
      
  build-windows:
    runs-on: windows-latest

    steps:
    
      - uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Install Dependencies
        run: |
          Invoke-Webrequest -URI https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe -OutFile ${{github.workspace}}\vulkan-sdk.exe
          ${{github.workspace}}\vulkan-sdk.exe --accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.32bit com.lunarg.vulkan.sdl2 com.lunarg.vulkan.glm com.lunarg.vulkan.volk com.lunarg.vulkan.vma com.lunarg.vulkan.debug com.lunarg.vulkan.debug32
          
          $var = Invoke-Webrequest -URI https://vulkan.lunarg.com/sdk/latest/windows.txt | Select-Object -ExpandProperty Content
          $env:VULKAN_SDK = "C:\VulkanSDK\$var\"
          
          ${{github.workspace}}\vcpkg\bootstrap-vcpkg.bat
          ${{github.workspace}}\vcpkg\vcpkg.exe integrate install
          
          ${{github.workspace}}\vcpkg\vcpkg.exe install assimp:x64-windows
          ${{github.workspace}}\vcpkg\vcpkg.exe install openexr:x64-windows
          ${{github.workspace}}\vcpkg\vcpkg.exe install sdl2[vulkan]:x64-windows
          ${{github.workspace}}\vcpkg\vcpkg.exe install stb:x64-windows
          ${{github.workspace}}\vcpkg\vcpkg.exe install vulkan:x64-windows
          
      - name: Configure CMake Build Debug
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          $var = Invoke-Webrequest -URI https://vulkan.lunarg.com/sdk/latest/windows.txt | Select-Object -ExpandProperty Content
          $env:VULKAN_SDK = "C:\VulkanSDK\$var\"
          
          cmake -B ${{github.workspace}}/build-windows/build-debug -DCMAKE_BUILD_TYPE=Debug -T ClangCL

      - name: Compile BananEngine Build Debug
        run: cmake --build ${{github.workspace}}/build-windows/build-debug
        
      - name: Configure CMake Build Release
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          $var = Invoke-Webrequest -URI https://vulkan.lunarg.com/sdk/latest/windows.txt | Select-Object -ExpandProperty Content
          $env:VULKAN_SDK = "C:\VulkanSDK\$var\"
          
          cmake -B ${{github.workspace}}/build-windows/build-release -DCMAKE_BUILD_TYPE=Release -T ClangCL

      - name: Compile BananEngine Build Release
        run: cmake --build ${{github.workspace}}/build-windows/build-release
        
      - name: Archive compilation output
        uses: actions/upload-artifact@v3
        with:
          name: Build Output Windows
          path: ${{github.workspace}}/build-windows/
          
        
        
